name: Scrape iCar to cars.json

on:
  workflow_dispatch: # מאפשר להריץ ידנית מה-Actions
  schedule:
    - cron: "0 0 * * *" # ירוץ פעם ביום בחצות

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run scraper
        run: node scraper.js

      - name: Commit and Push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add cars.json
          git commit -m "Update cars.json" || echo "No changes to commit"
          git push
