name: Scrape iCar to cars.json

on:
  workflow_dispatch:

jobs:
  step3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Verify Python
        run: |
          python --version
          echo "print('Hello from Python')" > test.py
          python test.py
