name: Scrape iCar to cars.json

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run scraper
        run: node scraper.js

      - name: Commit and Push result
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add cars.json
          git commit -m "Update cars.json"
          git push
