name: Scrape iCar to cars.json

on:
  workflow_dispatch:

jobs:
  step2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repo files
        run: |
          pwd
          ls -la
